In [2]:
import torch
import torch.nn as nn
import numpy as np

In [3]:
# make a linear layer:
#
l = nn.Linear(10, 2)

In [8]:
# make an input of size 10 (vocabulary size 100)
input_ids = torch.randint(0, 100, (1, 10))
print(input_ids)

tensor([[16,  3, 10, 35, 59, 66, 72, 83, 68, 63]])


In [14]:
# get the shape of the layer
l(input_ids)

RuntimeError: mat1 and mat2 must have the same dtype

In [24]:
# make a unit matrix
mat = torch.eye(5)
print(mat)

ones = torch.ones(5, 5)
print(ones)

rand = torch.rand(5, 5)
print(rand)

tril = torch.tril(ones)
print(tril)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0.3968, 0.2316, 0.7598, 0.0134, 0.2137],
        [0.8550, 0.9253, 0.1052, 0.4261, 0.9299],
        [0.4293, 0.4932, 0.8746, 0.8704, 0.3665],
        [0.1907, 0.2623, 0.5960, 0.9968, 0.0114],
        [0.7196, 0.4515, 0.6329, 0.2686, 0.5931]])
tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [26]:
tril @ rand # <- cumulative sum of the columns !

tensor([[0.3968, 0.2316, 0.7598, 0.0134, 0.2137],
        [1.2519, 1.1568, 0.8649, 0.4395, 1.1436],
        [1.6811, 1.6500, 1.7396, 1.3099, 1.5101],
        [1.8718, 1.9123, 2.3356, 2.3067, 1.5215],
        [2.5914, 2.3638, 2.9685, 2.5753, 2.1146]])

In [ ]:

print(torch.__version__)

flash = hasattr(torch.nn.functional, 'scaled_dot_product_attention')

print('flash attention available ? ', flash)

# With flash attention
# The script took 383.0676827430725 seconds to complete.

# Without
# The script took 428.0146815776825 seconds to complete.